### ISSUE TITLE
"pip3 install murre" failed because of pyomnttok dependency

### ISSUE THREAD

**Issue by silviachantal** [mikahama/murre#13]
I tried to install the library, but it fails on python versions 3.5, 3.6, 3.7, 3.8, 3.9, 3.11 on ubuntu 22.03.
For versions 3.5-3.8 the `pyomnttok` cannot be install due to no available mathing versions.
For versions above 3.8 tensorflow 2.4.0 is not available anymore.

To reproduce the issue the following conda environment yaml can be used.
`conda env create -f <path-to-file>
```yaml
name: murre
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    - murre==1.4.1
```
